[tool.poetry]
name = "{{ cookiecutter-package-name }}"
version = "0.1.0"
description = "{{ cookiecutter.short_description }}"
authors = ["{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>"]
readme = "README.md"
packages = [
    {include = "{{ cookiecutter.package_name ~ '_package'}}", from="src"}
]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"


[tool.poetry.group.dev.dependencies]
mypy = "*"
black = "*"
flake8 = "*"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
interrogate = "*"
isort = "*"
commitizen = "*"
ipykernel = "^6.17.1"
pandas-stubs = "*"
flake8-bugbear = "*"
sourcery = "*"

[tool.isort]
profile = "black"
import_heading_stdlib = "Python Standard Library Imports"
import_heading_thirdparty = "Third Party Imports"
import_heading_firstparty = "{{ cookiecutter.package_name }} Imports"
# src_paths = ["<path-to-src-code>"]
# known_first_party = ["<any packages defined locally>"]
# known_third_party = ["<any 3rd party packages with potential name collisions>"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
