version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  unit-tests:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run pytest tests
          name: Run unit tests

workflows:
  main:
    jobs:
      - unit-tests
