name: Test Cookie Cutter
on:
  push:
    branches:
      - main

jobs:
  test-cookie-cutter:
    name: "Test Cookie Cutter"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install Project
        run: uv sync

      - name: Run unit tests
        run: uv run pytest tests
